In [0]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Conv2D, MaxPooling2D, Flatten
from tensorflow.keras.datasets import fashion_mnist
from keras.utils import np_utils

In [2]:
(x_train, y_train),(x_test,y_test) = fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [3]:
x_train.shape

(60000, 28, 28)

In [4]:
y_train.shape

(60000,)

In [0]:
x_train = x_train.reshape(x_train.shape[0],x_train.shape[1],x_train.shape[2],1)
x_test = x_test.reshape(x_test.shape[0],x_test.shape[1],x_test.shape[2],1)

In [0]:
x_train = x_train/255
x_test = x_test/255

In [6]:
x_train.shape

(60000, 28, 28, 1)

In [7]:
import numpy as np
np.unique(y_train)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [0]:
y_train = np_utils.to_categorical(y_train,10)
y_test = np_utils.to_categorical(y_test,10)

In [10]:
y_train

array([[0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [0]:
model = Sequential()
model.add(Conv2D(32, (3,3),activation='relu',input_shape=(28,28,1))) ## 26,26,32
model.add(MaxPooling2D(2,2)) #13,13,32
model.add(Flatten())
model.add(Dense(32, activation='relu'))
model.add(Dense(10,activation='softmax'))


In [15]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 26, 26, 16)        160       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 13, 13, 16)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 2704)              0         
_________________________________________________________________
dense_2 (Dense)              (None, 32)                86560     
_________________________________________________________________
dense_3 (Dense)              (None, 10)                330       
Total params: 87,050
Trainable params: 87,050
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [20]:
model.fit(x_train,y_train,batch_size=200,epochs=10,validation_data=(x_test,y_test))

Epoch 1/10
300/300 [==============================] - 3s 9ms/step - loss: 0.7352 - accuracy: 0.7419 - val_loss: 0.4971 - val_accuracy: 0.8191
Epoch 2/10
300/300 [==============================] - 2s 8ms/step - loss: 0.4367 - accuracy: 0.8442 - val_loss: 0.4261 - val_accuracy: 0.8431
Epoch 3/10
300/300 [==============================] - 2s 8ms/step - loss: 0.3807 - accuracy: 0.8638 - val_loss: 0.3961 - val_accuracy: 0.8587
Epoch 4/10
300/300 [==============================] - 2s 8ms/step - loss: 0.3461 - accuracy: 0.8768 - val_loss: 0.3651 - val_accuracy: 0.8670
Epoch 5/10
300/300 [==============================] - 2s 8ms/step - loss: 0.3219 - accuracy: 0.8852 - val_loss: 0.3376 - val_accuracy: 0.8795
Epoch 6/10
300/300 [==============================] - 2s 8ms/step - loss: 0.3065 - accuracy: 0.8910 - val_loss: 0.3229 - val_accuracy: 0.8854
Epoch 7/10
300/300 [==============================] - 2s 8ms/step - loss: 0.2911 - accuracy: 0.8965 - val_loss: 0.3156 - val_accuracy: 0.8866
Epoch 

In [21]:
model.evaluate(x_test,y_test)

313/313 [==============================] - 1s 4ms/step - loss: 0.2963 - accuracy: 0.8937


[0.2963312864303589, 0.8937000036239624]

In [27]:
np.argmax(model.predict(x_test),axis=-1)

array([9, 2, 1, ..., 8, 1, 5])

In [28]:
model.predict(x_test)

array([[2.8840614e-06, 4.8039137e-09, 1.6801579e-06, ..., 2.0362278e-02,
        7.6529681e-04, 9.6337265e-01],
       [7.8794989e-04, 4.1443940e-08, 9.9768543e-01, ..., 3.6848649e-11,
        9.9462522e-07, 1.2478024e-08],
       [2.9988223e-05, 9.9984503e-01, 2.7748899e-06, ..., 8.0441652e-08,
        3.6774662e-07, 7.5186285e-10],
       ...,
       [2.2324042e-03, 2.8708637e-08, 1.5677458e-03, ..., 3.9311562e-06,
        9.8675621e-01, 3.5052682e-07],
       [7.7319044e-07, 9.9861157e-01, 3.1899430e-07, ..., 2.0832876e-07,
        2.3691825e-06, 6.3058918e-09],
       [4.4715681e-04, 8.1336320e-06, 8.8162610e-04, ..., 2.3306032e-01,
        8.0038629e-02, 5.5358415e-03]], dtype=float32)